#!/usr/bin/env python
from fabric.api import *

env.host_string = 'rtts.eu'
env.user = 'www'

local('rsync -av --delete django/ www@rtts.eu:moniquebroekman')

with cd('/home/www/moniquebroekman'):
    with prefix('workon monique'):
        run('./manage.py collectstatic')
        run('./manage.py syncdb')

env.user = 'origin'
sudo('killall -SIGHUP uwsgi')
