#!/usr/bin/env python
from r2src.deploy import *

host = 'www.moniquebroekman.nl'
aliases = ['moniquebroekman.nl', 'www.puckworks.nl', 'puckworks.nl']

bootstrap()
install('python-dev postgresql postgresql-server-dev-all')
setup_virtualenv('monique')

explain("Checking /srv/moniquebroekman")
dir_exists('/srv/moniquebroekman')
done()

explain("Checking database user 'monique'...")
with settings(hide('warnings'), sudo_user='postgres', warn_only=True):
    if sudo('psql -tc "select * from pg_user where usename = \'monique\';" | grep -q monique').failed:
        sudo('createuser -SRD monique')
    # creating db's simply fails if they already exist
    sudo('createdb -O monique monique')
    sudo('createdb -O monique monique')
done()

upload()

explain("Collecting static files...")
with cd(abspath('django')):
    vrun('monique', './manage.py collectstatic')
done()

explain("Syncing database...")
with cd(abspath('django')):
    vrun('monique', './manage.py syncdb')
done()

serve_dynamically(host, virtualenv='monique', media_url='/media', media_dir='/srv/moniquebroekman', static_dir=abspath('django/static'), chdir=abspath('django'), wsgi_file='mbcms/wsgi.py')

done('Deployment complete!')
