# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
