# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 23:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161130_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position'], 'verbose_name': 'pagina', 'verbose_name_plural': 'pagina’s'},
        ),
        migrations.AlterField(
            model_name='page',
            name='page_content',
            field=ckeditor.fields.RichTextField(verbose_name='inhoud'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(max_length=255, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(blank=True, verbose_name='positie'),
        ),
        migrations.AlterField(
            model_name='page',
            name='short_name',
            field=models.SlugField(help_text='deze naam wordt gebruikt in de URL', unique=True, verbose_name='verkorte naam'),
        ),
        migrations.AlterField(
            model_name='page',
            name='visible_in_menu',
            field=models.BooleanField(default=True, verbose_name='zichtbaar in het menu'),
        ),
    ]
