# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 19:36
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='datum')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='tekst')),
            ],
        ),
    ]
