# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
            ],
            options={
                'verbose_name_plural': 'afbeeldingen',
                'ordering': ['position'],
                'verbose_name': 'afbeelding',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube of Vimeo link'),
        ),
        migrations.AddField(
            model_name='photo',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.Blog'),
        ),
    ]
