# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 09:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170621_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='tekst')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube of Vimeo link')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.Blog')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Sectie',
            },
        ),
    ]
