# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_section_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='element',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
