# Generated by Django 3.1.1 on 2020-09-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170916_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='section',
            name='html',
            field=models.TextField(blank=True, help_text='Plak hier de broncode van een volledig HTML document.', verbose_name='HTML'),
        ),
    ]
