# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 16:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('short_name', models.SlugField(unique=True)),
                ('visible_in_menu', models.BooleanField(default=True)),
                ('page_content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
