# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 16:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('short_name', models.SlugField(unique=True)),
                ('visible_in_menu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categorieën',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_title', models.CharField(max_length=255)),
                ('short_name', models.SlugField(unique=True)),
                ('frontpage_summary', ckeditor.fields.RichTextField()),
                ('article_content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'projecten',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='categories', to='portfolio.Project'),
        ),
    ]
