# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-position'], 'verbose_name_plural': 'projecten'},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='positie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='positie'),
            preserve_default=False,
        ),
    ]
