# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 23:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20161130_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position'], 'verbose_name': 'categorie', 'verbose_name_plural': 'categorieën'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position'], 'verbose_name_plural': 'projecten'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='afbeelding'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255, verbose_name='naam van deze categorie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='categories', to='portfolio.Project', verbose_name='projecten'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_name',
            field=models.SlugField(help_text='deze naam wordt gebruikt in de URL', unique=True, verbose_name='verkorte naam'),
        ),
        migrations.AlterField(
            model_name='category',
            name='visible_in_menu',
            field=models.BooleanField(default=True, verbose_name='zichtbaar in het menu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='article_content',
            field=ckeditor.fields.RichTextField(verbose_name='inhoud'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontpage_summary',
            field=ckeditor.fields.RichTextField(verbose_name='samenvatting'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='gewijzigd'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=255, verbose_name='titel van het project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.SlugField(help_text='deze naam wordt gebruikt in de URL', unique=True, verbose_name='verkorte naam'),
        ),
    ]
