# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20161214_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible_on_homepage',
            field=models.BooleanField(default=True, verbose_name='zichtbaar op de homepage'),
        ),
    ]
