# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_category_visible_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='afbeelding'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, verbose_name='samenvatting'),
        ),
    ]
