# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 15:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20170110_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('type', models.CharField(choices=[('text', 'Tekst'), ('photo', 'Foto'), ('video', 'Video')], help_text='Kies hier het type element. Een foto-element laat de gekozen foto zien, een video-element toont een video, en een tekst-element geeft tekts weer.', max_length=16)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube of Vimeo link')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='tekst')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name_plural': 'elementen',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='article_content',
            field=ckeditor.fields.RichTextField(verbose_name='inhoud (oude stijl)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontpage_summary',
            field=ckeditor.fields.RichTextField(verbose_name='samenvatting (oude stijl)'),
        ),
        migrations.AddField(
            model_name='element',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
        ),
    ]
