# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20170110_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'afbeelding',
                'verbose_name_plural': 'afbeeldingen',
            },
        ),
        migrations.RemoveField(
            model_name='element',
            name='image',
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('text', 'Tekst element (geeft alleen tekst weer)'), ('photo', 'Foto element (geeft foto’s weer)'), ('video', 'Video element (geeft een video weer)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='article_content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud (oude stijl)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontpage_summary',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='samenvatting (oude stijl)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=255, verbose_name='titel'),
        ),
        migrations.AddField(
            model_name='photo',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Element'),
        ),
    ]
