# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 19:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20170112_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='portfolio.Project'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.Element'),
        ),
        migrations.AlterField(
            model_name='project',
            name='article_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Probeer deze editor niet meer te gebruiken! Voeg in plaats daarvan foto-, video- of tekstelementen hieronder toe.', verbose_name='inhoud (oude stijl)'),
        ),
    ]
